### PR TITLE
fix msg delete bug on multiple format commands

### LINKED ISSUE #15: Bot crashes on /format command without code-input followed by subsequent /format command with input
## Describe the bug
If you enter one /format command without entering any input and then after that do a new /format command followed by correct code input the bot crashes with a Discord API error. Error msg:

**DiscordAPIError: Unknown Message**
    at RequestHandler.execute (/home/mikejoh12/projects/community-bot/node_modules/discord.js/src/rest/RequestHandler.js:298:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async RequestHandler.push (/home/mikejoh12/projects/community-bot/node_modules/discord.js/src/rest/RequestHandler.js:50:14)
    at async MessageManager.delete (/home/mikejoh12/projects/community-bot/node_modules/discord.js/src/managers/MessageManager.js:205:5) {
  **method: 'delete',**
  path: '/channels/941104975411544155/messages/947520583728529449',
  code: 10008,
  httpStatus: 404,
  requestData: { json: undefined, files: [] }
}

## Expected behavior
The bot should not crash when entering multiple /format commands even if the first command does not have any code entered.

## To Reproduce
1. Do a /format command without entering any code.
2. Do another /format command and enter code.
3. See error in the console.

## Additional context
This is a rejected promise error which crashes in Node 16. We could do a global handler for rejected promises as was done in the codecademy-discord-bot. But we should also address the issue in the command file. It is a delete error and is likely associated with this line: 
`  interaction.channel.messages.delete(msg.id);`

### PR DESCRIPTION
**Pull request by mikejoh12**
## What issue is this solving?

Closes #15

### Description
There is a bug in the /format command if you enter just the command more than one time before entering some code to format. The bot crashes with an Unhandled Promise Rejection with a DiscordAPIError/Unknown Message when the format command is trying to delete a nonexistent message.

## Any helpful knowledge/context for the reviewer?
In this case 2+ /format commands are both listening for 60 seconds for code input. Only one of them deletes the msg and therefore there is a bug when the other command tries to delete the same msg. Implemented fix as described here  to ignore error logging due to unknown message errors: https://discordjs.guide/popular-topics/errors.html#code 

We may also handle promise rejections globally in a separate PR as an additional barrier to API errors.

- Is a re-seeding of the database necessary? No
- Any new dependencies to install? No
- Any special requirements to test? No
  - (e.g., admin perms, alt account, etc.)

### Please make sure you've attempted to meet the following coding standards
- [X] Code has been tested and does not produce errors
- [X] Code is readable and formatted
- [X] There isn't any unnecessary commented-out code

### CODE REVIEW

File: src/commands/format.js [hunk 1]
```diff
@@ -38,7 +39,12 @@ async function formatCode(interaction) {
 
   const msg = messages.first();
   const code = msg.content;
-  interaction.channel.messages.delete(msg.id);
+
+  interaction.channel.messages.delete(msg.id).catch((error) => {
+    if (error.code !== Constants.APIErrors.UNKNOWN_MESSAGE) {
+      console.error('Failed to delete the message:', error);
+    }
```
Comment (aedwardg) [inline src/commands/format.js:46]: So this ignores the error if it's the `UNKNOWN_MESSAGE` error?

Comment (mikejoh12) [reply src/commands/format.js:46]: Yes, that is correct. I just did it as demonstrated in the docs. The bug was caused by trying to delete an already deleted msg.

**Review by aedwardg — APPROVED** [review]
Seems solid 👍

**Review by ashstewart7 — APPROVED** [review]
LGTM!
